#!/bin/sh

echo Try to bring net interface up ...>/dev/console

source /etc/nettype.conf
if [ -f /etc/net.conf ] ; then
	source /etc/net.conf

	if [ $NETTYPE -eq 1 ] ; then
	#ÓÐÏßÍøÂç
		if [ $DHCP -eq 1 ] ; then
		#dhcp set eth0
			ifconfig eth0 down
			ifconfig eth0 up
			udhcpc -b -i eth0
		#dhcp set eth1
			ifconfig eth1 down
			ifconfig eth1 up
			udhcpc -b -i eth1
		else
		#manual set eth0
			ifconfig eth0 down
			ifconfig eth0 hw ether $MAC0
			echo ifconfig eth0 hw ether $MAC0 >/dev/console
			ifconfig eth0 $IPADDR0 netmask $NETMASK0 up
			echo ifconfig eth0 $IPADDR0 netmask $NETMASK0 up >/dev/console
			route add default gw $GATEWAY0
			echo add default gw $GATEWAY0 >/dev/console
		#manual set eth1
			ifconfig eth1 down
			ifconfig eth1 hw ether $MAC1
			echo ifconfig eth1 hw ether $MAC1 >/dev/console
			ifconfig eth1 $IPADDR1 netmask $NETMASK1 up
			echo ifconfig eth1 $IPADDR1 netmask $NETMASK1 up >/dev/console
			route add default gw $GATEWAY1
			echo add default gw $GATEWAY1 >/dev/console
		fi
	fi
fi

echo Done > /dev/console
