#!/bin/sh


PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#

mount -a
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mount -n -t usbfs none /proc/bus/usb
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
mkdir -p /var/lock

mount -t vfat /dev/mmcblk1p1 /run/media/mmcblk1p1
mount -t ext4 /dev/mmcblk1p2 /run/media/mmcblk1p2
mount -t ext4 /dev/mmcblk1p3 /run/media/mmcblk1p3
mount -t ext4 /dev/mmcblk1p4 /run/media/mmcblk1p4

hwclock -s
#EmbedSky_wdg &

#pda &

#insmod /lib/input-polldev.ko
#insmod /lib/mac80211.ko
#TL-WN321G+
#insmod /lib/rt2x00lib.ko
#insmod /lib/rt2x00usb.ko
#insmod /lib/rt73usb.ko
#TL-WN322G+
#insmod /lib/zd1211rw.ko

#insmod /lib/ov9650.ko
#insmod /lib/camera.ko
#modprobe zd1211rw
#modprobe rt73usb
#modprobe rt5370sta
insmod /lib/modules/drivers/ads7846.ko
ifconfig lo 127.0.0.1
net_set &

#/etc/rc.d/init.d/leds start
#/etc/rc.d/init.d/netd start
#/etc/rc.d/init.d/httpd start
insmod /opt/dsp_mailbox.ko
mknod /dev/dsp_mailbox c 246 0
/home/root/spi -D /dev/spidev1.0
/opt/dsploader /ftp/AM57xx_DSP1DEMO.out dsp1

vsftpd &
chown root:root /etc/vsftpd.conf
/bin/hostname -F /etc/sysconfig/HOSTNAME
