#!/bin/sh


PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#

mount -a
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mount -n -t usbfs none /proc/bus/usb
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
mkdir -p /var/lock

#hwclock -s
#EmbedSky_wdg &

#pda &

#insmod /lib/input-polldev.ko
#insmod /lib/mac80211.ko
#TL-WN321G+
#insmod /lib/rt2x00lib.ko
#insmod /lib/rt2x00usb.ko
#insmod /lib/rt73usb.ko
#TL-WN322G+
#insmod /lib/zd1211rw.ko

#insmod /lib/ov9650.ko
#insmod /lib/camera.ko
#modprobe zd1211rw
#modprobe rt73usb
#modprobe rt5370sta

ifconfig lo 127.0.0.1
net_set &

#/etc/rc.d/init.d/leds start
#/etc/rc.d/init.d/netd start
#/etc/rc.d/init.d/httpd start

/bin/hostname -F /etc/sysconfig/HOSTNAME
